<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Pokemon Chooser</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

        <script src="/js/vue/vue.js"></script>
        <script src="/js/vue-resource/vue-resource.js"></script>
        <script src="/js/vue-strap/vue-strap.js"></script>
    </head>
    <body>

        <div class="container" id="app">
            <div class="page-header">
                <h1>Pokemon Chooser <small>{{ message }}</small></h1>
            </div>

        </div>

        <script src="/js/app.js"></script>
    </body>
</html>
